<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\BankingDDD.CommonLibrary\Common\Common.csproj" />
    <ProjectReference Include="..\..\BankingApp.AccountManagement\AccountManagement.Core\AccountManagement.Core.csproj" />
    <ProjectReference Include="..\UserManagement.Core\UserManagement.Core.csproj" />
  </ItemGroup>

</Project>
