// <auto-generated/>
#pragma warning disable CS0618
using BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.GetLoanByParam.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.GetLoanByParam
{
    /// <summary>
    /// Builds and executes requests for operations under \api\LoanApplication\GetLoanByParam
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetLoanByParamRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the BankingDDD.ServiceClients.ApiGateway.api.LoanApplication.GetLoanByParam.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.GetLoanByParam.Item.WithApplicationNumberItemRequestBuilder"/></returns>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.GetLoanByParam.Item.WithApplicationNumberItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("applicationNumber", position);
                return new global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.GetLoanByParam.Item.WithApplicationNumberItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.GetLoanByParam.GetLoanByParamRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetLoanByParamRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/LoanApplication/GetLoanByParam", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.GetLoanByParam.GetLoanByParamRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetLoanByParamRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/LoanApplication/GetLoanByParam", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
