// <auto-generated />
using System;
using BankingApp.AccountManagement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BankingApp.AccountManagement.Migrations
{
    [DbContext(typeof(AccountDbContext))]
    [Migration("20251206144524_InitialAccountManagement")]
    partial class InitialAccountManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("MySimpleSequence")
                .StartsAt(1000001L)
                .HasMin(-2000000L)
                .HasMax(2000000L)
                .IsCyclic();

            modelBuilder.Entity("BankingApp.AccountManagement.Core.Accounts.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AccountNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"MySimpleSequence\"')");

                    b.Property<int>("AccountStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AccountUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CloasedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountStatusId");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("BankingApp.AccountManagement.Core.Accounts.Entities.AccountStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("AccountStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Opened"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Locked"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Closed"
                        });
                });

            modelBuilder.Entity("BankingApp.AccountManagement.Core.Accounts.Entities.AccountType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("AccountType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Savings"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Current"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Loan"
                        },
                        new
                        {
                            Id = 4,
                            Name = "PPF"
                        });
                });

            modelBuilder.Entity("BankingApp.AccountManagement.Core.Accounts.Entities.BeneficiaryGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Beneficaries", (string)null);
                });

            modelBuilder.Entity("BankingApp.AccountManagement.Core.Accounts.Entities.Credit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Credits", (string)null);
                });

            modelBuilder.Entity("BankingApp.AccountManagement.Core.Accounts.Entities.Debit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Debits", (string)null);
                });

            modelBuilder.Entity("BankingApp.AccountManagement.Core.Banks.Entities.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Bank", (string)null);
                });

            modelBuilder.Entity("BankingApp.AccountManagement.Core.Branches.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("Branches", (string)null);
                });

            modelBuilder.Entity("BankingApp.AccountManagement.Core.Customers.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("NumberOfAccounts")
                        .HasColumnType("integer");

                    b.HasKey("CustomerId");

                    b.ToTable("AccountCustomers", (string)null);
                });

            modelBuilder.Entity("BankingApp.AccountManagement.Core.Accounts.Entities.Account", b =>
                {
                    b.HasOne("BankingApp.AccountManagement.Core.Accounts.Entities.AccountStatus", "AccountStatus")
                        .WithMany()
                        .HasForeignKey("AccountStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankingApp.AccountManagement.Core.Accounts.Entities.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankingApp.AccountManagement.Core.Customers.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountStatus");

                    b.Navigation("AccountType");
                });

            modelBuilder.Entity("BankingApp.AccountManagement.Core.Accounts.Entities.BeneficiaryGroup", b =>
                {
                    b.HasOne("BankingApp.AccountManagement.Core.Accounts.Entities.Account", null)
                        .WithMany("BeneficiaryGroups")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BankingApp.AccountManagement.Core.Accounts.ValueObjects.Beneficiary", "Beneficiary", b1 =>
                        {
                            b1.Property<Guid>("BeneficiaryGroupId")
                                .HasColumnType("uuid");

                            b1.Property<int>("BeneficaryAccountNo")
                                .HasColumnType("integer")
                                .HasColumnName("BeneficaryAccountNo");

                            b1.Property<string>("BeneficaryBankName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("BeneficaryBankName");

                            b1.Property<string>("BeneficaryName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("BeneficaryName");

                            b1.HasKey("BeneficiaryGroupId");

                            b1.ToTable("Beneficaries");

                            b1.WithOwner()
                                .HasForeignKey("BeneficiaryGroupId");
                        });

                    b.Navigation("Beneficiary")
                        .IsRequired();
                });

            modelBuilder.Entity("BankingApp.AccountManagement.Core.Accounts.Entities.Credit", b =>
                {
                    b.HasOne("BankingApp.AccountManagement.Core.Accounts.Entities.Account", null)
                        .WithMany("Credits")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BankingAppDDD.Domains.Abstractions.ValueObjects.Amount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("CreditId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("Value");

                            b1.HasKey("CreditId");

                            b1.ToTable("Credits");

                            b1.WithOwner()
                                .HasForeignKey("CreditId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("BankingApp.AccountManagement.Core.Accounts.Entities.Debit", b =>
                {
                    b.HasOne("BankingApp.AccountManagement.Core.Accounts.Entities.Account", null)
                        .WithMany("Debits")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BankingAppDDD.Domains.Abstractions.ValueObjects.Amount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("DebitId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("CreditAmount");

                            b1.HasKey("DebitId");

                            b1.ToTable("Debits");

                            b1.WithOwner()
                                .HasForeignKey("DebitId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("BankingApp.AccountManagement.Core.Banks.Entities.Bank", b =>
                {
                    b.OwnsOne("BankingAppDDD.Domains.Abstractions.ValueObjects.Address", "BankAddress", b1 =>
                        {
                            b1.Property<Guid>("BankId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Country");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ZipCode");

                            b1.HasKey("BankId");

                            b1.ToTable("Bank");

                            b1.WithOwner()
                                .HasForeignKey("BankId");
                        });

                    b.OwnsOne("BankingAppDDD.Domains.Abstractions.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("BankId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("BankId");

                            b1.ToTable("Bank");

                            b1.WithOwner()
                                .HasForeignKey("BankId");
                        });

                    b.Navigation("BankAddress")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("BankingApp.AccountManagement.Core.Branches.Entities.Branch", b =>
                {
                    b.HasOne("BankingApp.AccountManagement.Core.Banks.Entities.Bank", null)
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BankingAppDDD.Domains.Abstractions.ValueObjects.Address", "BranchAddress", b1 =>
                        {
                            b1.Property<Guid>("BranchId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Country");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ZipCode");

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.OwnsOne("BankingAppDDD.Domains.Abstractions.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("BranchId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.Navigation("BranchAddress")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("BankingApp.AccountManagement.Core.Accounts.Entities.Account", b =>
                {
                    b.Navigation("BeneficiaryGroups");

                    b.Navigation("Credits");

                    b.Navigation("Debits");
                });
#pragma warning restore 612, 618
        }
    }
}
