apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-data
spec:
  accessModes:
    # ReadWriteOnce means the volume can be mounted as read-write by a single node
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi # Request 1GiB of storage (adjust as needed)
---

apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  selector:
    app: pgadmin
  type: ClusterIP
  ports:
    - name: "5050"  
      port: 5050
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  labels:
    app: pgadmin
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      imagePullSecrets:
      - name: bankingapp-secret
      containers:
        - name: pgadmin
          image: bankingappacr.azurecr.io/dpage/pgadmin4:1.1 # Using the latest official seq image
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin@admin.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "admin"
          volumeMounts:
            - mountPath: /var/lib/pgadmin
              name: pgadmin-data
      restartPolicy: Always
      volumes:
        - name: pgadmin-data
          persistentVolumeClaim:
            claimName: pgadmin-data
      