
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Request 10GB of storage
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      imagePullSecrets:
      - name: bankingapp-secret
      containers:
        - name: postgres
          image: bankingappacr.azurecr.io/postgres:16.4 # Use the latest PostgreSQL image
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: keycloak_db
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_HOST_AUTH_METHOD
              value: scram-sha-256
            - name: POSTGRES_INITDB_ARGS
              value: --auth-host=scram-sha-256
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: DB_APP_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_APP_USER_PASS
            - name: DB_KEYCLOAK_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_KEYCLOAK_USER_PASS
          envFrom:
            - configMapRef:
                name: postgres-configmap # Reference to the ConfigMap
          livenessProbe:
            exec:
              command:
                - pg_isready 
                - "-U"
                - "keycloak"
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-claim1
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgres-claim1
---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  type: LoadBalancer # Expose the service internally within the cluster