apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
stringData:
  password: "keycloakpassword"
  # Passwords for the specific app users
  DB_APP_USER_PASS: "Alm1ghty1"
  DB_KEYCLOAK_USER_PASS: "keycloakpassword"
