apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seq-pvc
spec:
  accessModes:
    - ReadWriteOnce # This access mode works for most single-node deployments
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: seq
spec:
  selector:
    app: seq
  type: LoadBalancer
  ports:
    - name: "5341"  
      port: 5341
      targetPort: 5341
    - name: "8081"
      port: 8081
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq-deployment
  labels:
    app: seq
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: seq
  template:
    metadata:
      labels:
        app: seq
    spec:
      imagePullSecrets:
      - name: bankingapp-secret
      containers:
        - name: seq
          image: bankingappacr.azurecr.io/datalust/seq:2024.4 # Using the latest official seq image
          ports:
            - containerPort: 5341
              protocol: TCP
            - containerPort: 80
              protocol: TCP
          env:
            - name: ACCEPT_EULA
              value: "Y"
          volumeMounts:
            - name: seq-data
              mountPath: /data # Mount path for persistent data
      volumes:
        - name: seq-data
          persistentVolumeClaim:
            claimName: seq-pvc
         
      
      