<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="CustomerAccount\IntegrationEvents\" />
    <Folder Include="Transfer\MappingProfile\" />
    <Folder Include="Transfer\Validations\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.5.2" />
    <PackageReference Include="Microsoft.Extensions.ML" Version="5.0.0" />
    <PackageReference Include="Polly" Version="8.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\BankingDDD.Application\Applications\Applications.csproj" />
    <ProjectReference Include="..\AccountManagement.Core\AccountManagement.Core.csproj" />
  </ItemGroup>

</Project>
