// <auto-generated/>
#pragma warning disable CS0618
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Customer.Getcustomeraccountcount.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BankingDDD.ServiceClients.ApiGateway.Api.V2.Customer.Getcustomeraccountcount
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\customer\getcustomeraccountcount
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetcustomeraccountcountRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the BankingDDD.ServiceClients.ApiGateway.api.v2.customer.getcustomeraccountcount.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Customer.Getcustomeraccountcount.Item.GetcustomeraccountcountItemRequestBuilder"/></returns>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Customer.Getcustomeraccountcount.Item.GetcustomeraccountcountItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Customer.Getcustomeraccountcount.Item.GetcustomeraccountcountItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the BankingDDD.ServiceClients.ApiGateway.api.v2.customer.getcustomeraccountcount.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Customer.Getcustomeraccountcount.Item.GetcustomeraccountcountItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Customer.Getcustomeraccountcount.Item.GetcustomeraccountcountItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Customer.Getcustomeraccountcount.Item.GetcustomeraccountcountItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Customer.Getcustomeraccountcount.GetcustomeraccountcountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetcustomeraccountcountRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/customer/getcustomeraccountcount", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Customer.Getcustomeraccountcount.GetcustomeraccountcountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetcustomeraccountcountRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/customer/getcustomeraccountcount", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
