// <auto-generated/>
#pragma warning disable CS0618
using BankingDDD.ServiceClients.ApiGateway.Api.Account.AddAccount;
using BankingDDD.ServiceClients.ApiGateway.Api.Account.AddBeneficiary;
using BankingDDD.ServiceClients.ApiGateway.Api.Account.CloseAccount;
using BankingDDD.ServiceClients.ApiGateway.Api.Account.Deposit;
using BankingDDD.ServiceClients.ApiGateway.Api.Account.GetAccountStatus;
using BankingDDD.ServiceClients.ApiGateway.Api.Account.Withdraw;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BankingDDD.ServiceClients.ApiGateway.Api.Account
{
    /// <summary>
    /// Builds and executes requests for operations under \api\Account
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccountRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The AddAccount property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.Account.AddAccount.AddAccountRequestBuilder AddAccount
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.Account.AddAccount.AddAccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The AddBeneficiary property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.Account.AddBeneficiary.AddBeneficiaryRequestBuilder AddBeneficiary
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.Account.AddBeneficiary.AddBeneficiaryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CloseAccount property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.Account.CloseAccount.CloseAccountRequestBuilder CloseAccount
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.Account.CloseAccount.CloseAccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Deposit property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.Account.Deposit.DepositRequestBuilder Deposit
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.Account.Deposit.DepositRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetAccountStatus property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.Account.GetAccountStatus.GetAccountStatusRequestBuilder GetAccountStatus
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.Account.GetAccountStatus.GetAccountStatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Withdraw property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.Account.Withdraw.WithdrawRequestBuilder Withdraw
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.Account.Withdraw.WithdrawRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.Account.AccountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Account", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.Account.AccountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Account", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
