// <auto-generated/>
#pragma warning disable CS0618
using BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.AcceptLoanApplication;
using BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.CreateDebtorInfo;
using BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.CreateLoanApplication;
using BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.EvaluateLoanApplication;
using BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.GetLoanById;
using BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.GetLoanByParam;
using BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.RejectLoanApplication;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication
{
    /// <summary>
    /// Builds and executes requests for operations under \api\LoanApplication
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LoanApplicationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The AcceptLoanApplication property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.AcceptLoanApplication.AcceptLoanApplicationRequestBuilder AcceptLoanApplication
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.AcceptLoanApplication.AcceptLoanApplicationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CreateDebtorInfo property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.CreateDebtorInfo.CreateDebtorInfoRequestBuilder CreateDebtorInfo
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.CreateDebtorInfo.CreateDebtorInfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The CreateLoanApplication property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.CreateLoanApplication.CreateLoanApplicationRequestBuilder CreateLoanApplication
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.CreateLoanApplication.CreateLoanApplicationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The EvaluateLoanApplication property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.EvaluateLoanApplication.EvaluateLoanApplicationRequestBuilder EvaluateLoanApplication
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.EvaluateLoanApplication.EvaluateLoanApplicationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetLoanById property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.GetLoanById.GetLoanByIdRequestBuilder GetLoanById
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.GetLoanById.GetLoanByIdRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetLoanByParam property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.GetLoanByParam.GetLoanByParamRequestBuilder GetLoanByParam
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.GetLoanByParam.GetLoanByParamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The RejectLoanApplication property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.RejectLoanApplication.RejectLoanApplicationRequestBuilder RejectLoanApplication
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.RejectLoanApplication.RejectLoanApplicationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.LoanApplicationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LoanApplicationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/LoanApplication", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.LoanApplicationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LoanApplicationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/LoanApplication", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
