// <auto-generated/>
#pragma warning disable CS0618
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Addaccount;
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Addbeneficiary;
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Closeaccount;
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Deposit;
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Getaccountstatus;
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Withdraw;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BankingDDD.ServiceClients.ApiGateway.Api.V2.Account
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\account
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccountRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The addaccount property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Addaccount.AddaccountRequestBuilder Addaccount
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Addaccount.AddaccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The addbeneficiary property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Addbeneficiary.AddbeneficiaryRequestBuilder Addbeneficiary
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Addbeneficiary.AddbeneficiaryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The closeaccount property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Closeaccount.CloseaccountRequestBuilder Closeaccount
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Closeaccount.CloseaccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deposit property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Deposit.DepositRequestBuilder Deposit
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Deposit.DepositRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getaccountstatus property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Getaccountstatus.GetaccountstatusRequestBuilder Getaccountstatus
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Getaccountstatus.GetaccountstatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The withdraw property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Withdraw.WithdrawRequestBuilder Withdraw
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Withdraw.WithdrawRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.AccountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/account", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.AccountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/account", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
