// <auto-generated/>
#pragma warning disable CS0618
using BankingDDD.ServiceClients.ApiGateway.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Evaluateloanapplication
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\loanapplication\evaluateloanapplication
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EvaluateloanapplicationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Evaluateloanapplication.EvaluateloanapplicationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EvaluateloanapplicationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/loanapplication/evaluateloanapplication", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Evaluateloanapplication.EvaluateloanapplicationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EvaluateloanapplicationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/loanapplication/evaluateloanapplication", rawUrl)
        {
        }
        /// <returns>A <see cref="global::BankingDDD.ServiceClients.ApiGateway.Models.Envelope"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::BankingDDD.ServiceClients.ApiGateway.Models.Envelope">When receiving a 400 status code</exception>
        /// <exception cref="global::BankingDDD.ServiceClients.ApiGateway.Models.Envelope">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::BankingDDD.ServiceClients.ApiGateway.Models.Envelope?> PutAsync(global::BankingDDD.ServiceClients.ApiGateway.Models.EvaluateLoanApplicationCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::BankingDDD.ServiceClients.ApiGateway.Models.Envelope> PutAsync(global::BankingDDD.ServiceClients.ApiGateway.Models.EvaluateLoanApplicationCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::BankingDDD.ServiceClients.ApiGateway.Models.Envelope.CreateFromDiscriminatorValue },
                { "404", global::BankingDDD.ServiceClients.ApiGateway.Models.Envelope.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::BankingDDD.ServiceClients.ApiGateway.Models.Envelope>(requestInfo, global::BankingDDD.ServiceClients.ApiGateway.Models.Envelope.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::BankingDDD.ServiceClients.ApiGateway.Models.EvaluateLoanApplicationCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::BankingDDD.ServiceClients.ApiGateway.Models.EvaluateLoanApplicationCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Evaluateloanapplication.EvaluateloanapplicationRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Evaluateloanapplication.EvaluateloanapplicationRequestBuilder WithUrl(string rawUrl)
        {
            return new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Evaluateloanapplication.EvaluateloanapplicationRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EvaluateloanapplicationRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
