apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-claim0
spec:
  accessModes:
    # ReadWriteOnce means the volume can be mounted as read-write by a single node
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi # Request 1GiB of storage (adjust as needed)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: bankingappacr.azurecr.io/bankingappddd-keycloak:1.1  # Use a specific version in production
        livenessProbe:
            exec:
              command:
                - "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        - containerPort: 9000
          protocol: TCP
        env:
        # General Keycloak settings
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL_DATABASE
          value: "keycloak_db" # Required if running behind a reverse proxy/ingress
        - name: KC_HTTP_PORT
          value: "8080"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HOSTNAME_BACKCHANNEL_DYNAMIC
          value: "false"
        - name: KC_DB_URL
          value: "jdbc:postgresql://postgres:5432/keycloak_db"
        - name: KC_HOSTNAME_BACKCHANNEL
          value: "http://keycloak:8080"
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: "admin"
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: "admin"
        # Database connection settings from ConfigMap
        - name: KC_DB_URL_HOST
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: DB_HOST
        - name: KC_DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: DB_DATABASE
        - name: KC_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_HOSTNAME
        # Database credentials from Secret
        - name: KC_DB_USERNAME 
          valueFrom:
            secretKeyRef:
              name: keycloak-db-credentials
              key: username
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-db-credentials
              key: password
        # Initial admin credentials (change for production)
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
            - mountPath: /opt/keycloak/data/import
              name: keycloak-claim0
      restartPolicy: Always
      volumes:
        - name: keycloak-claim0
          persistentVolumeClaim:
            claimName: keycloak-claim0
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  selector:
    app: keycloak
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "9000"
      port: 9000
      targetPort: 9000
  type: ClusterIP # Use ClusterIP for internal access, or LoadBalancer/NodePort for external access