apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
spec:
  accessModes:
    # Common access modes are ReadWriteOnce, ReadOnlyMany, ReadWriteMany
    # MongoDB typically requires a volume that can be mounted as ReadWriteOnce
    - ReadWriteOnce
  resources:
    # Define how much storage you need
    requests:
      storage: 10Gi 
  storageClassName: default
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-config
spec:
  accessModes:
    # ReadWriteOnce means the volume can be mounted as read-write by a single node
    - ReadWriteOnce
  storageClassName: default 
  resources:
    requests:
      storage: 1Gi # Request 1GiB of storage (adjust as needed)
---


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
spec:
  serviceName: "mongo"   
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      initContainers:
      - name: change-ownership-container
        image: busybox
        command: ["/bin/chown","-R","1000:1000", "/data/db"]
        securityContext:
          runAsUser: 0
          privileged: true
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        - name: mongo-config
          mountPath: /data/configdb
      containers:
        - name: mongodb
          image: bankingappacr.azurecr.io/mongo:8.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - echo 'db.runCommand("ping").ok' | mongosh --port 27017 --quiet
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          ports:
            - containerPort: 27017
              protocol: TCP
          env:
          - name: APP_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: mongo-configmap # The name of your ConfigMap
                key: connection_string    # The key within the ConfigMap
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-root-username 
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-root-password
          volumeMounts:
            - mountPath: /data/configdb
              name: mongo-config
            - mountPath: /data/db
              name: mongo-data
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-config
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongodb-data

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017