
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi # Request 10GB of storage
---

apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
spec:
  containers:
    - name: postgres
      image: bankingappacr.azurecr.io/postgres:16.4 # Use the latest PostgreSQL image
      imagePullPolicy: IfNotPresent
      livenessProbe:
        exec:
          command:
            - pg_isready -U keycloak
        failureThreshold: 5
        periodSeconds: 10
        timeoutSeconds: 5
        ports:
          - containerPort: 5432
            protocol: TCP
        env:
          - name: POSTGRES_DB
            value: keycloak_db
          - name: POSTGRES_USER
            value: keycloak
          - name: POSTGRES_HOST_AUTH_METHOD
            value: scram-sha-256
          - name: POSTGRES_INITDB_ARGS
            value: --auth-host=scram-sha-256
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret # Reference a Kubernetes Secret for the password
                key: password
              configMapRef:
                name: postgres-secret
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-cm0
          - mountPath: /docker-entrypoint-initdb.d
            name: postgres-claim1
      volumes:
        - configMap:
            name: postgres-cm0
          name: postgres-cm0
        - name: postgres-claim1
          persistentVolumeClaim:
            claimName: postgres-claim1
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  type: ClusterIP # Expose the service internally within the cluster