apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
spec:
  accessModes:
    # ReadWriteOnce means the volume can be mounted as read-write by a single node
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi # Request 1GiB of storage (adjust as needed)
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis-container
          image: bankingappacr.azurecr.io/redis:latest # Using the latest official Redis image
          livenessProbe:
            exec:
              command:
                - redis-cli ping | grep PONG
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /docker_data/redis
              name: redis-data
      restartPolicy: Always
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
          