
apiVersion: v1
kind: Service
metadata:
  name: seq-input-gelf-service
  labels:
    app: seq-input-gelf
spec:
  selector:
    app: seq-input-gelf
  ports:
    - name: "12201"
      port: 12201
      protocol: UDP
      targetPort: 12201

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq-input-gelf-deployment
  labels:
    app: seq-input-gelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seq-input-gelf
  template:
    metadata:
      labels:
        app: seq-input-gelf
    spec:
      containers:
        - name: seq-input-gelf
          image: bankingappacr.azurecr.io/datalust/seq-input-gelf:latest # Using the latest official seq image
          ports:
            - containerPort: 12201
              protocol: UDP
          env:
            - name: SEQ_ADDRESS
              value: http://seq:5341
      restartPolicy: Always
      