
apiVersion: v1
kind: Service
metadata:
  name: seq
spec:
  selector:
    app: seq
  type: LoadBalancer
  ports:
    - name: "5341"  
      port: 5341
      targetPort: 5341
    - name: "8081"
      port: 8081
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq-deployment
  labels:
    app: seq
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: seq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: seq
    spec:
      containers:
        - name: seq
          image: bankingappacr.azurecr.io/datalust/seq:2024.3 # Using the latest official seq image
          livenessProbe:
            exec:
              command:
                - /seqsvr/Client/seqcli node health -s http://localhost
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 10
          ports:
            - containerPort: 5341
              protocol: TCP
            - containerPort: 80
              protocol: TCP
          env:
            - name: ACCEPT_EULA
              value: "Y"
      restartPolicy: Always
      