// <auto-generated/>
#pragma warning disable CS0618
using BankingDDD.ServiceClients.ApiGateway.Api.Account;
using BankingDDD.ServiceClients.ApiGateway.Api.Auth;
using BankingDDD.ServiceClients.ApiGateway.Api.Bank;
using BankingDDD.ServiceClients.ApiGateway.Api.Branch;
using BankingDDD.ServiceClients.ApiGateway.Api.Customer;
using BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication;
using BankingDDD.ServiceClients.ApiGateway.Api.Operator;
using BankingDDD.ServiceClients.ApiGateway.Api.Value;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BankingDDD.ServiceClients.ApiGateway.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Account property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.Account.AccountRequestBuilder Account
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.Account.AccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Auth property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.Auth.AuthRequestBuilder Auth
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Bank property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.Bank.BankRequestBuilder Bank
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.Bank.BankRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Branch property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.Branch.BranchRequestBuilder Branch
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.Branch.BranchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Customer property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.Customer.CustomerRequestBuilder Customer
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.Customer.CustomerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The LoanApplication property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.LoanApplicationRequestBuilder LoanApplication
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.LoanApplication.LoanApplicationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Operator property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.Operator.OperatorRequestBuilder Operator
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.Operator.OperatorRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Value property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.Value.ValueRequestBuilder Value
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.Value.ValueRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
