// <auto-generated/>
#pragma warning disable CS0618
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Getaccount.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Getaccount
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\account\getaccount
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetaccountRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the BankingDDD.ServiceClients.ApiGateway.api.v2.account.getaccount.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Getaccount.Item.WithCustomerItemRequestBuilder"/></returns>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Getaccount.Item.WithCustomerItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("customerid", position);
                return new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Getaccount.Item.WithCustomerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the BankingDDD.ServiceClients.ApiGateway.api.v2.account.getaccount.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Getaccount.Item.WithCustomerItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Getaccount.Item.WithCustomerItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("customerid", position);
                return new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Getaccount.Item.WithCustomerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Getaccount.GetaccountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetaccountRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/account/getaccount", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.Getaccount.GetaccountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetaccountRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/account/getaccount", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
