// <auto-generated/>
#pragma warning disable CS0618
using BankingDDD.ServiceClients.ApiGateway.Api.Branch.BranchDetails;
using BankingDDD.ServiceClients.ApiGateway.Api.Branch.Item;
using BankingDDD.ServiceClients.ApiGateway.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace BankingDDD.ServiceClients.ApiGateway.Api.Branch
{
    /// <summary>
    /// Builds and executes requests for operations under \api\Branch
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BranchRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The branchDetails property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.Branch.BranchDetails.BranchDetailsRequestBuilder BranchDetails
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.Branch.BranchDetails.BranchDetailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the BankingDDD.ServiceClients.ApiGateway.api.Branch.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.Branch.Item.BranchItemRequestBuilder"/></returns>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.Branch.Item.BranchItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::BankingDDD.ServiceClients.ApiGateway.Api.Branch.Item.BranchItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the BankingDDD.ServiceClients.ApiGateway.api.Branch.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.Branch.Item.BranchItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::BankingDDD.ServiceClients.ApiGateway.Api.Branch.Item.BranchItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::BankingDDD.ServiceClients.ApiGateway.Api.Branch.Item.BranchItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.Branch.BranchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BranchRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Branch", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.Branch.BranchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BranchRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Branch", rawUrl)
        {
        }
        /// <returns>A <see cref="global::BankingDDD.ServiceClients.ApiGateway.Models.CreatedResultEnvelope"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::BankingDDD.ServiceClients.ApiGateway.Models.Envelope">When receiving a 400 status code</exception>
        /// <exception cref="global::BankingDDD.ServiceClients.ApiGateway.Models.Envelope">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::BankingDDD.ServiceClients.ApiGateway.Models.CreatedResultEnvelope?> PostAsync(global::BankingDDD.ServiceClients.ApiGateway.Models.AddBranchCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::BankingDDD.ServiceClients.ApiGateway.Models.CreatedResultEnvelope> PostAsync(global::BankingDDD.ServiceClients.ApiGateway.Models.AddBranchCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::BankingDDD.ServiceClients.ApiGateway.Models.Envelope.CreateFromDiscriminatorValue },
                { "404", global::BankingDDD.ServiceClients.ApiGateway.Models.Envelope.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::BankingDDD.ServiceClients.ApiGateway.Models.CreatedResultEnvelope>(requestInfo, global::BankingDDD.ServiceClients.ApiGateway.Models.CreatedResultEnvelope.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::BankingDDD.ServiceClients.ApiGateway.Models.AddBranchCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::BankingDDD.ServiceClients.ApiGateway.Models.AddBranchCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.Branch.BranchRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.Branch.BranchRequestBuilder WithUrl(string rawUrl)
        {
            return new global::BankingDDD.ServiceClients.ApiGateway.Api.Branch.BranchRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BranchRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
