// <auto-generated />
using System;
using BankingApp.LoanManagement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BankingApp.LoanManagement.Migrations
{
    [DbContext(typeof(CreditMgmtDbContext))]
    partial class CreditMgmtDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BankingApp.LoanManagement.Application.LoanApplicationModels.LoanType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("LoanTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mortgage"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Home"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Car"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Personal"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Gold"
                        });
                });

            modelBuilder.Entity("BankingApp.LoanManagement.Core.DebtInfos.Entities.DebtorInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdentificationNumber")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("DebtorInfos", (string)null);
                });

            modelBuilder.Entity("BankingApp.LoanManagement.Core.LoanApplicationsEntities.LoanApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("LoanTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LoanApplications", (string)null);
                });

            modelBuilder.Entity("BankingApp.LoanManagement.Core.LoanApplicationsEntities.Operator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Operators", (string)null);
                });

            modelBuilder.Entity("BankingApp.LoanManagement.Core.DebtInfos.Entities.DebtorInfo", b =>
                {
                    b.OwnsMany("BankingApp.LoanManagement.Core.DebtInfos.ValueObjects.Debt", "Debts", b1 =>
                        {
                            b1.Property<Guid>("DebtorInfoId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.HasKey("DebtorInfoId", "Id");

                            b1.ToTable("Debt");

                            b1.WithOwner()
                                .HasForeignKey("DebtorInfoId");
                        });

                    b.Navigation("Debts");
                });

            modelBuilder.Entity("BankingApp.LoanManagement.Core.LoanApplicationsEntities.LoanApplication", b =>
                {
                    b.OwnsOne("BankingApp.LoanManagement.Core.LoanApplications.ValueObjects.Asset", "Asset", b1 =>
                        {
                            b1.Property<Guid>("LoanApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("PropertyValueAmount");

                            b1.HasKey("LoanApplicationId");

                            b1.ToTable("LoanApplications");

                            b1.WithOwner()
                                .HasForeignKey("LoanApplicationId");

                            b1.OwnsOne("BankingAppDDD.Domains.Abstractions.ValueObjects.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("AssetLoanApplicationId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("ZipCode")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("AssetLoanApplicationId");

                                    b2.ToTable("LoanApplications");

                                    b2.WithOwner()
                                        .HasForeignKey("AssetLoanApplicationId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.OwnsOne("BankingApp.LoanManagement.Core.LoanApplications.ValueObjects.Customer", "Customer", b1 =>
                        {
                            b1.Property<Guid>("LoanApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("BirthDate")
                                .HasColumnType("date")
                                .HasColumnName("BirthDate");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid")
                                .HasColumnName("CustomerId");

                            b1.HasKey("LoanApplicationId");

                            b1.ToTable("LoanApplications");

                            b1.WithOwner()
                                .HasForeignKey("LoanApplicationId");

                            b1.OwnsOne("BankingAppDDD.Domains.Abstractions.ValueObjects.Amount", "MonthlyIncome", b2 =>
                                {
                                    b2.Property<Guid>("CustomerLoanApplicationId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Value")
                                        .HasColumnType("numeric")
                                        .HasColumnName("MonthlyIncomeAmount");

                                    b2.HasKey("CustomerLoanApplicationId");

                                    b2.ToTable("LoanApplications");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerLoanApplicationId");
                                });

                            b1.Navigation("MonthlyIncome")
                                .IsRequired();
                        });

                    b.OwnsOne("BankingApp.LoanManagement.Core.LoanApplications.ValueObjects.Loan", "Loan", b1 =>
                        {
                            b1.Property<Guid>("LoanApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("LoanNumberOfYears")
                                .HasColumnType("integer");

                            b1.HasKey("LoanApplicationId");

                            b1.ToTable("LoanApplications");

                            b1.WithOwner()
                                .HasForeignKey("LoanApplicationId");

                            b1.OwnsOne("BankingAppDDD.Domains.Abstractions.ValueObjects.Amount", "LoanAmount", b2 =>
                                {
                                    b2.Property<Guid>("LoanApplicationId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Value")
                                        .HasColumnType("numeric")
                                        .HasColumnName("LoanAmount");

                                    b2.HasKey("LoanApplicationId");

                                    b2.ToTable("LoanApplications");

                                    b2.WithOwner()
                                        .HasForeignKey("LoanApplicationId");
                                });

                            b1.OwnsOne("BankingAppDDD.Domains.Abstractions.ValueObjects.Percent", "InterestRate", b2 =>
                                {
                                    b2.Property<Guid>("LoanApplicationId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Value")
                                        .HasColumnType("numeric")
                                        .HasColumnName("InterestRate");

                                    b2.HasKey("LoanApplicationId");

                                    b2.ToTable("LoanApplications");

                                    b2.WithOwner()
                                        .HasForeignKey("LoanApplicationId");
                                });

                            b1.Navigation("InterestRate")
                                .IsRequired();

                            b1.Navigation("LoanAmount")
                                .IsRequired();
                        });

                    b.OwnsOne("BankingApp.LoanManagement.Core.LoanApplications.ValueObjects.LoanUnderWriter", "Decision", b1 =>
                        {
                            b1.Property<Guid>("LoanApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("DecisionBy")
                                .HasColumnType("uuid")
                                .HasColumnName("DecisionBy");

                            b1.Property<DateOnly>("DecisionDate")
                                .HasColumnType("date");

                            b1.HasKey("LoanApplicationId");

                            b1.ToTable("LoanApplications");

                            b1.WithOwner()
                                .HasForeignKey("LoanApplicationId");
                        });

                    b.OwnsOne("BankingApp.LoanManagement.Core.LoanApplications.ValueObjects.Registration", "Registration", b1 =>
                        {
                            b1.Property<Guid>("LoanApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("RegisteredBy")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("RegistrationDate")
                                .HasColumnType("date");

                            b1.HasKey("LoanApplicationId");

                            b1.ToTable("LoanApplications");

                            b1.WithOwner()
                                .HasForeignKey("LoanApplicationId");
                        });

                    b.OwnsOne("BankingApp.LoanManagement.Core.LoanApplications.ValueObjects.ScoringResult", "Score", b1 =>
                        {
                            b1.Property<Guid>("LoanApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Explanation")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Score")
                                .HasColumnType("text")
                                .HasColumnName("ScoringResult");

                            b1.HasKey("LoanApplicationId");

                            b1.ToTable("LoanApplications");

                            b1.WithOwner()
                                .HasForeignKey("LoanApplicationId");
                        });

                    b.Navigation("Asset")
                        .IsRequired();

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Decision")
                        .IsRequired();

                    b.Navigation("Loan")
                        .IsRequired();

                    b.Navigation("Registration")
                        .IsRequired();

                    b.Navigation("Score")
                        .IsRequired();
                });

            modelBuilder.Entity("BankingApp.LoanManagement.Core.LoanApplicationsEntities.Operator", b =>
                {
                    b.OwnsOne("BankingAppDDD.Domains.Abstractions.ValueObjects.Amount", "CompetenceLevel", b1 =>
                        {
                            b1.Property<Guid>("OperatorId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("CompetenceLevelAmount");

                            b1.HasKey("OperatorId");

                            b1.ToTable("Operators");

                            b1.WithOwner()
                                .HasForeignKey("OperatorId");
                        });

                    b.Navigation("CompetenceLevel")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
