// <auto-generated/>
#pragma warning disable CS0618
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Value.GetAdmin;
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Value.GetGeneral;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BankingDDD.ServiceClients.ApiGateway.Api.V2.Value
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\value
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ValueRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The getAdmin property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Value.GetAdmin.GetAdminRequestBuilder GetAdmin
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Value.GetAdmin.GetAdminRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getGeneral property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Value.GetGeneral.GetGeneralRequestBuilder GetGeneral
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Value.GetGeneral.GetGeneralRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Value.ValueRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ValueRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/value", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Value.ValueRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ValueRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/value", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
