// <auto-generated/>
#pragma warning disable CS0618
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Account;
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Auth;
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Bank;
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Branch;
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Customer;
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication;
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Operator;
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Value;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BankingDDD.ServiceClients.ApiGateway.Api.V2
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V2RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The account property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.AccountRequestBuilder Account
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Account.AccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The auth property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Auth.AuthRequestBuilder Auth
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bank property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Bank.BankRequestBuilder Bank
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Bank.BankRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The branch property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Branch.BranchRequestBuilder Branch
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Branch.BranchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The customer property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Customer.CustomerRequestBuilder Customer
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Customer.CustomerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The loanapplication property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.LoanapplicationRequestBuilder Loanapplication
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.LoanapplicationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The operator property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Operator.OperatorRequestBuilder Operator
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Operator.OperatorRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The value property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Value.ValueRequestBuilder Value
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Value.ValueRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
