// <auto-generated/>
#pragma warning disable CS0618
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Acceptloanapplication;
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.CreatedebtorInfo;
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Createloanapplication;
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Evaluateloanapplication;
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Getloanbyid;
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Getloanbyparam;
using BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Rejectloanapplication;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\loanapplication
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LoanapplicationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The acceptloanapplication property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Acceptloanapplication.AcceptloanapplicationRequestBuilder Acceptloanapplication
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Acceptloanapplication.AcceptloanapplicationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The createdebtorInfo property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.CreatedebtorInfo.CreatedebtorInfoRequestBuilder CreatedebtorInfo
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.CreatedebtorInfo.CreatedebtorInfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The createloanapplication property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Createloanapplication.CreateloanapplicationRequestBuilder Createloanapplication
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Createloanapplication.CreateloanapplicationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The evaluateloanapplication property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Evaluateloanapplication.EvaluateloanapplicationRequestBuilder Evaluateloanapplication
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Evaluateloanapplication.EvaluateloanapplicationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getloanbyid property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Getloanbyid.GetloanbyidRequestBuilder Getloanbyid
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Getloanbyid.GetloanbyidRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getloanbyparam property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Getloanbyparam.GetloanbyparamRequestBuilder Getloanbyparam
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Getloanbyparam.GetloanbyparamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rejectloanapplication property</summary>
        public global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Rejectloanapplication.RejectloanapplicationRequestBuilder Rejectloanapplication
        {
            get => new global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.Rejectloanapplication.RejectloanapplicationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.LoanapplicationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LoanapplicationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/loanapplication", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BankingDDD.ServiceClients.ApiGateway.Api.V2.Loanapplication.LoanapplicationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LoanapplicationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/loanapplication", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
