// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BankingDDD.ServiceClients.ApiGateway.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AccountDTO : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accountId property</summary>
        public Guid? AccountId { get; set; }
        /// <summary>The accountNo property</summary>
        public int? AccountNo { get; set; }
        /// <summary>The accountStatusId property</summary>
        public int? AccountStatusId { get; set; }
        /// <summary>The accountTypeId property</summary>
        public int? AccountTypeId { get; set; }
        /// <summary>The accountUpdatedDate property</summary>
        public DateTimeOffset? AccountUpdatedDate { get; set; }
        /// <summary>The customerId property</summary>
        public Guid? CustomerId { get; set; }
        /// <summary>The dateAdded property</summary>
        public DateTimeOffset? DateAdded { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BankingDDD.ServiceClients.ApiGateway.Models.AccountDTO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BankingDDD.ServiceClients.ApiGateway.Models.AccountDTO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BankingDDD.ServiceClients.ApiGateway.Models.AccountDTO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountId", n => { AccountId = n.GetGuidValue(); } },
                { "accountNo", n => { AccountNo = n.GetIntValue(); } },
                { "accountStatusId", n => { AccountStatusId = n.GetIntValue(); } },
                { "accountTypeId", n => { AccountTypeId = n.GetIntValue(); } },
                { "accountUpdatedDate", n => { AccountUpdatedDate = n.GetDateTimeOffsetValue(); } },
                { "customerId", n => { CustomerId = n.GetGuidValue(); } },
                { "dateAdded", n => { DateAdded = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("accountId", AccountId);
            writer.WriteIntValue("accountNo", AccountNo);
            writer.WriteIntValue("accountStatusId", AccountStatusId);
            writer.WriteIntValue("accountTypeId", AccountTypeId);
            writer.WriteDateTimeOffsetValue("accountUpdatedDate", AccountUpdatedDate);
            writer.WriteGuidValue("customerId", CustomerId);
            writer.WriteDateTimeOffsetValue("dateAdded", DateAdded);
        }
    }
}
#pragma warning restore CS0618
