// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BankingDDD.ServiceClients.ApiGateway.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AddBeneficiaryCommand : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accountId property</summary>
        public Guid? AccountId { get; set; }
        /// <summary>The beneficiaryAccount property</summary>
        public int? BeneficiaryAccount { get; set; }
        /// <summary>The beneficiaryBankName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BeneficiaryBankName { get; set; }
#nullable restore
#else
        public string BeneficiaryBankName { get; set; }
#endif
        /// <summary>The beneficiaryName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BeneficiaryName { get; set; }
#nullable restore
#else
        public string BeneficiaryName { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BankingDDD.ServiceClients.ApiGateway.Models.AddBeneficiaryCommand"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BankingDDD.ServiceClients.ApiGateway.Models.AddBeneficiaryCommand CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BankingDDD.ServiceClients.ApiGateway.Models.AddBeneficiaryCommand();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountId", n => { AccountId = n.GetGuidValue(); } },
                { "beneficiaryAccount", n => { BeneficiaryAccount = n.GetIntValue(); } },
                { "beneficiaryBankName", n => { BeneficiaryBankName = n.GetStringValue(); } },
                { "beneficiaryName", n => { BeneficiaryName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("accountId", AccountId);
            writer.WriteIntValue("beneficiaryAccount", BeneficiaryAccount);
            writer.WriteStringValue("beneficiaryBankName", BeneficiaryBankName);
            writer.WriteStringValue("beneficiaryName", BeneficiaryName);
        }
    }
}
#pragma warning restore CS0618
