// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace BankingDDD.ServiceClients.ApiGateway.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustomerDTO : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The customerId property</summary>
        public Guid? CustomerId { get; set; }
        /// <summary>The customerTypeId property</summary>
        public int? CustomerTypeId { get; set; }
        /// <summary>The dateAdded property</summary>
        public DateTimeOffset? DateAdded { get; set; }
        /// <summary>The dateOfBirth property</summary>
        public Date? DateOfBirth { get; set; }
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The loanStatus property</summary>
        public int? LoanStatus { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The permanentAddress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::BankingDDD.ServiceClients.ApiGateway.Models.AddressDTO? PermanentAddress { get; set; }
#nullable restore
#else
        public global::BankingDDD.ServiceClients.ApiGateway.Models.AddressDTO PermanentAddress { get; set; }
#endif
        /// <summary>The phoneNo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneNo { get; set; }
#nullable restore
#else
        public string PhoneNo { get; set; }
#endif
        /// <summary>The updatedOn property</summary>
        public DateTimeOffset? UpdatedOn { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BankingDDD.ServiceClients.ApiGateway.Models.CustomerDTO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BankingDDD.ServiceClients.ApiGateway.Models.CustomerDTO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BankingDDD.ServiceClients.ApiGateway.Models.CustomerDTO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "customerId", n => { CustomerId = n.GetGuidValue(); } },
                { "customerTypeId", n => { CustomerTypeId = n.GetIntValue(); } },
                { "dateAdded", n => { DateAdded = n.GetDateTimeOffsetValue(); } },
                { "dateOfBirth", n => { DateOfBirth = n.GetDateValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "loanStatus", n => { LoanStatus = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "permanentAddress", n => { PermanentAddress = n.GetObjectValue<global::BankingDDD.ServiceClients.ApiGateway.Models.AddressDTO>(global::BankingDDD.ServiceClients.ApiGateway.Models.AddressDTO.CreateFromDiscriminatorValue); } },
                { "phoneNo", n => { PhoneNo = n.GetStringValue(); } },
                { "updatedOn", n => { UpdatedOn = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("customerId", CustomerId);
            writer.WriteIntValue("customerTypeId", CustomerTypeId);
            writer.WriteDateTimeOffsetValue("dateAdded", DateAdded);
            writer.WriteDateValue("dateOfBirth", DateOfBirth);
            writer.WriteStringValue("email", Email);
            writer.WriteIntValue("loanStatus", LoanStatus);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::BankingDDD.ServiceClients.ApiGateway.Models.AddressDTO>("permanentAddress", PermanentAddress);
            writer.WriteStringValue("phoneNo", PhoneNo);
            writer.WriteDateTimeOffsetValue("updatedOn", UpdatedOn);
        }
    }
}
#pragma warning restore CS0618
