// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace BankingDDD.ServiceClients.ApiGateway.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LoanApplicationDTO : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The customerBirthDate property</summary>
        public Date? CustomerBirthDate { get; set; }
        /// <summary>The customerId property</summary>
        public Guid? CustomerId { get; set; }
        /// <summary>The customerMonthlyIncome property</summary>
        public double? CustomerMonthlyIncome { get; set; }
        /// <summary>The decisionBy property</summary>
        public Guid? DecisionBy { get; set; }
        /// <summary>The decisionDate property</summary>
        public Date? DecisionDate { get; set; }
        /// <summary>The explanation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Explanation { get; set; }
#nullable restore
#else
        public string Explanation { get; set; }
#endif
        /// <summary>The interestRate property</summary>
        public double? InterestRate { get; set; }
        /// <summary>The loanAmount property</summary>
        public double? LoanAmount { get; set; }
        /// <summary>The loanApplicationNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LoanApplicationNumber { get; set; }
#nullable restore
#else
        public string LoanApplicationNumber { get; set; }
#endif
        /// <summary>The loanId property</summary>
        public Guid? LoanId { get; set; }
        /// <summary>The loanNoOfYears property</summary>
        public int? LoanNoOfYears { get; set; }
        /// <summary>The loanTypeId property</summary>
        public int? LoanTypeId { get; set; }
        /// <summary>The propertyAddress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::BankingDDD.ServiceClients.ApiGateway.Models.AddressDTO? PropertyAddress { get; set; }
#nullable restore
#else
        public global::BankingDDD.ServiceClients.ApiGateway.Models.AddressDTO PropertyAddress { get; set; }
#endif
        /// <summary>The propertyValue property</summary>
        public double? PropertyValue { get; set; }
        /// <summary>The registeredBy property</summary>
        public Guid? RegisteredBy { get; set; }
        /// <summary>The registrationDate property</summary>
        public Date? RegistrationDate { get; set; }
        /// <summary>The scoringResult property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScoringResult { get; set; }
#nullable restore
#else
        public string ScoringResult { get; set; }
#endif
        /// <summary>The status property</summary>
        public int? Status { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BankingDDD.ServiceClients.ApiGateway.Models.LoanApplicationDTO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BankingDDD.ServiceClients.ApiGateway.Models.LoanApplicationDTO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BankingDDD.ServiceClients.ApiGateway.Models.LoanApplicationDTO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "customerBirthDate", n => { CustomerBirthDate = n.GetDateValue(); } },
                { "customerId", n => { CustomerId = n.GetGuidValue(); } },
                { "customerMonthlyIncome", n => { CustomerMonthlyIncome = n.GetDoubleValue(); } },
                { "decisionBy", n => { DecisionBy = n.GetGuidValue(); } },
                { "decisionDate", n => { DecisionDate = n.GetDateValue(); } },
                { "explanation", n => { Explanation = n.GetStringValue(); } },
                { "interestRate", n => { InterestRate = n.GetDoubleValue(); } },
                { "loanAmount", n => { LoanAmount = n.GetDoubleValue(); } },
                { "loanApplicationNumber", n => { LoanApplicationNumber = n.GetStringValue(); } },
                { "loanId", n => { LoanId = n.GetGuidValue(); } },
                { "loanNoOfYears", n => { LoanNoOfYears = n.GetIntValue(); } },
                { "loanTypeId", n => { LoanTypeId = n.GetIntValue(); } },
                { "propertyAddress", n => { PropertyAddress = n.GetObjectValue<global::BankingDDD.ServiceClients.ApiGateway.Models.AddressDTO>(global::BankingDDD.ServiceClients.ApiGateway.Models.AddressDTO.CreateFromDiscriminatorValue); } },
                { "propertyValue", n => { PropertyValue = n.GetDoubleValue(); } },
                { "registeredBy", n => { RegisteredBy = n.GetGuidValue(); } },
                { "registrationDate", n => { RegistrationDate = n.GetDateValue(); } },
                { "scoringResult", n => { ScoringResult = n.GetStringValue(); } },
                { "status", n => { Status = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateValue("customerBirthDate", CustomerBirthDate);
            writer.WriteGuidValue("customerId", CustomerId);
            writer.WriteDoubleValue("customerMonthlyIncome", CustomerMonthlyIncome);
            writer.WriteGuidValue("decisionBy", DecisionBy);
            writer.WriteDateValue("decisionDate", DecisionDate);
            writer.WriteStringValue("explanation", Explanation);
            writer.WriteDoubleValue("interestRate", InterestRate);
            writer.WriteDoubleValue("loanAmount", LoanAmount);
            writer.WriteStringValue("loanApplicationNumber", LoanApplicationNumber);
            writer.WriteGuidValue("loanId", LoanId);
            writer.WriteIntValue("loanNoOfYears", LoanNoOfYears);
            writer.WriteIntValue("loanTypeId", LoanTypeId);
            writer.WriteObjectValue<global::BankingDDD.ServiceClients.ApiGateway.Models.AddressDTO>("propertyAddress", PropertyAddress);
            writer.WriteDoubleValue("propertyValue", PropertyValue);
            writer.WriteGuidValue("registeredBy", RegisteredBy);
            writer.WriteDateValue("registrationDate", RegistrationDate);
            writer.WriteStringValue("scoringResult", ScoringResult);
            writer.WriteIntValue("status", Status);
        }
    }
}
#pragma warning restore CS0618
