// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace BankingDDD.ServiceClients.ApiGateway.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LoanApplicationSearchCriteriaDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The decisionBy property</summary>
        public Guid? DecisionBy { get; set; }
        /// <summary>The decisionDate property</summary>
        public Date? DecisionDate { get; set; }
        /// <summary>The loanAmount property</summary>
        public double? LoanAmount { get; set; }
        /// <summary>The loanApplicationNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LoanApplicationNumber { get; set; }
#nullable restore
#else
        public string LoanApplicationNumber { get; set; }
#endif
        /// <summary>The status property</summary>
        public int? Status { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BankingDDD.ServiceClients.ApiGateway.Models.LoanApplicationSearchCriteriaDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BankingDDD.ServiceClients.ApiGateway.Models.LoanApplicationSearchCriteriaDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BankingDDD.ServiceClients.ApiGateway.Models.LoanApplicationSearchCriteriaDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "decisionBy", n => { DecisionBy = n.GetGuidValue(); } },
                { "decisionDate", n => { DecisionDate = n.GetDateValue(); } },
                { "loanAmount", n => { LoanAmount = n.GetDoubleValue(); } },
                { "loanApplicationNumber", n => { LoanApplicationNumber = n.GetStringValue(); } },
                { "status", n => { Status = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("decisionBy", DecisionBy);
            writer.WriteDateValue("decisionDate", DecisionDate);
            writer.WriteDoubleValue("loanAmount", LoanAmount);
            writer.WriteStringValue("loanApplicationNumber", LoanApplicationNumber);
            writer.WriteIntValue("status", Status);
        }
    }
}
#pragma warning restore CS0618
