// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BankingDDD.ServiceClients.ApiGateway.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LoanApplicationData : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The assetData property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::BankingDDD.ServiceClients.ApiGateway.Models.AssetData? AssetData { get; set; }
#nullable restore
#else
        public global::BankingDDD.ServiceClients.ApiGateway.Models.AssetData AssetData { get; set; }
#endif
        /// <summary>The customerData property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::BankingDDD.ServiceClients.ApiGateway.Models.LoanApplicationCustomerData? CustomerData { get; set; }
#nullable restore
#else
        public global::BankingDDD.ServiceClients.ApiGateway.Models.LoanApplicationCustomerData CustomerData { get; set; }
#endif
        /// <summary>The loanData property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::BankingDDD.ServiceClients.ApiGateway.Models.LoanData? LoanData { get; set; }
#nullable restore
#else
        public global::BankingDDD.ServiceClients.ApiGateway.Models.LoanData LoanData { get; set; }
#endif
        /// <summary>The loanTypeId property</summary>
        public int? LoanTypeId { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BankingDDD.ServiceClients.ApiGateway.Models.LoanApplicationData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BankingDDD.ServiceClients.ApiGateway.Models.LoanApplicationData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BankingDDD.ServiceClients.ApiGateway.Models.LoanApplicationData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assetData", n => { AssetData = n.GetObjectValue<global::BankingDDD.ServiceClients.ApiGateway.Models.AssetData>(global::BankingDDD.ServiceClients.ApiGateway.Models.AssetData.CreateFromDiscriminatorValue); } },
                { "customerData", n => { CustomerData = n.GetObjectValue<global::BankingDDD.ServiceClients.ApiGateway.Models.LoanApplicationCustomerData>(global::BankingDDD.ServiceClients.ApiGateway.Models.LoanApplicationCustomerData.CreateFromDiscriminatorValue); } },
                { "loanData", n => { LoanData = n.GetObjectValue<global::BankingDDD.ServiceClients.ApiGateway.Models.LoanData>(global::BankingDDD.ServiceClients.ApiGateway.Models.LoanData.CreateFromDiscriminatorValue); } },
                { "loanTypeId", n => { LoanTypeId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::BankingDDD.ServiceClients.ApiGateway.Models.AssetData>("assetData", AssetData);
            writer.WriteObjectValue<global::BankingDDD.ServiceClients.ApiGateway.Models.LoanApplicationCustomerData>("customerData", CustomerData);
            writer.WriteObjectValue<global::BankingDDD.ServiceClients.ApiGateway.Models.LoanData>("loanData", LoanData);
            writer.WriteIntValue("loanTypeId", LoanTypeId);
        }
    }
}
#pragma warning restore CS0618
